FROM node:0.10.38

RUN mkdir /src

WORKDIR /src
ADD package.json /src/package.json
RUN npm install

EXPOSE 80

ENV VCAP_APP_PORT=80

#UPDATE IP BELOW
ENV CUSTOMER_SERVICE=nginx/acmeair
ENV MONGO_HOST=mongo

CMD node authservice_app.js 
