FROM node:latest

RUN mkdir /src

WORKDIR /src
ADD package.json /src/package.json
RUN npm install

EXPOSE 80

ENV VCAP_APP_PORT=80

#UPDATE IP BELOW
ENV AUTH_SERVICE=nginx/acmeair
ENV MONGO_HOST=customer_db

CMD node customerservice_app.js 
