FROM node:latest

RUN mkdir /src

WORKDIR /src
ADD package.json /src/package.json
RUN npm install

EXPOSE 80

ENV VCAP_APP_PORT=80

#UPDATE IP BELOW
ENV MONGO_HOST=flight_db

CMD node flightservice_app.js 
