FROM node:0.10.38

RUN mkdir /src

WORKDIR /src
ADD package.json /src/package.json
RUN npm install

EXPOSE 80

ENV VCAP_APP_PORT=80

#Update IP Below
ENV AUTH_SERVICE=nginx/acmeair
ENV MONGO_HOST=mongo2

CMD node bookingservice_app.js 
